# Generated by Django 4.0.2 on 2022-03-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sviz',
            fields=[
                ('Id_title', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('one', models.IntegerField(default=0)),
                ('two', models.IntegerField(default=0)),
                ('three', models.IntegerField(default=0)),
                ('four', models.IntegerField(default=0)),
                ('five', models.IntegerField(default=0)),
                ('six', models.IntegerField(default=0)),
                ('seven', models.IntegerField(default=0)),
                ('eight', models.IntegerField(default=0)),
            ],
        ),
    ]
