# Generated by Django 4.0.2 on 2022-03-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0003_staistik'),
    ]

    operations = [
        migrations.AddField(
            model_name='staistik',
            name='posetit',
            field=models.IntegerField(default=0),
        ),
    ]
