# Generated by Django 4.0.2 on 2022-03-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0005_remove_staistik_id_alter_staistik_exponat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staistik',
            name='completeness',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='staistik',
            name='description',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='staistik',
            name='visualFeedback',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
    ]
