# Generated by Django 4.0.2 on 2022-03-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0006_alter_staistik_completeness_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staistik',
            name='completeness',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='staistik',
            name='description',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='staistik',
            name='visualFeedback',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
