# Generated by Django 4.0.2 on 2022-03-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0008_staistik_zal_1_staistik_zal_2_staistik_zal_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staistik',
            name='target',
            field=models.FileField(default='/static/img/met.zpt', upload_to='upload/'),
        ),
    ]
