# Generated by Django 4.0.2 on 2022-03-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0011_remove_records_target_sviz_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='sviz',
            name='photo',
            field=models.ImageField(default='/static/img/аист.jpg', upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='sviz',
            name='target',
            field=models.FileField(default='/static/img/met.zpt', upload_to='img/'),
        ),
    ]
