# Generated by Django 4.0.2 on 2022-03-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0012_sviz_photo_alter_sviz_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='sviz',
            name='zametki',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
